### ISSUE TITLE
Support for MariaDB

### ISSUE THREAD

**Issue by emilknievel** [steven-ferguson/knex-cleaner#10]
Would be great if there was support for mariasql as the knex client.

**Comment by kibertoad** [comment]
Considering that Maria is mostly compatible with MySQL, couldn't same SQL be reused for Maria?.. What client id is used for maria?

**Comment by emilknievel** [comment]
Yeah, I tried to set host to mysql and it worked! One important thing to keep in mind though is that when MariaDB is used the 'database' attribute is called 'db' in knex, so it's easy to mix those up.

**Comment by kibertoad** [comment]
I'm not sure issue should be closed, it would be better if knex-cleaner recognized the "mariasql" as the valid option.

**Comment by paulogdm** [comment]
Closse this issue already. `mariasql` is not in active development state and you should migrate to `mysql` adapter. Lots os troubles using it with "objection.js" and "knex"....

**Comment by emilknievel** [comment]
Uh-huh
