### ISSUE TITLE
Does not support different schemas in postgres

### ISSUE THREAD

**Issue by dmorgantini** [steven-ferguson/knex-cleaner#24]
Currently, the library is limited to only working on the 'public' schema.  Is this by choice or would a pull request help?

https://github.com/steven-ferguson/knex-cleaner/blob/master/lib/knex_tables.js#L22

**Comment by rockrep** [comment]
👍 would like an schema option

**Comment by DanHulton** [comment]
There's an open PR for this, actually: https://github.com/steven-ferguson/knex-cleaner/pull/33

**Comment by steven-ferguson** [comment]
This should now be supported in 1.3
